import 'package:database/src/sql_database.dart';

/// Type definition for a log id.
typedef LogId = int;

/// {@template log}
/// Model for a log entry.
/// {@endtemplate}
class LogModel {
  /// {@macro log}
  LogModel({
    required this.id,
    required this.timestamp,
    required this.level,
    required this.message,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Creates a new [LogModel] without an ID (for insertion).
  /// The ID will be auto-generated by the database.
  LogModel.create({
    required this.timestamp,
    required this.level,
    required this.message,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) : id = 0,
       createdAt = createdAt ?? DateTime.now(),
       updatedAt = updatedAt ?? DateTime.now();

  /// Creates a [LogModel] from a a [Log] table instance.
  factory LogModel.fromTable(Log data) => LogModel(
    id: data.id,
    timestamp: data.timestamp,
    level: data.level,
    message: data.message,
    createdAt: data.createdAt,
    updatedAt: data.updatedAt,
  );

  /// Converts the [DailyTaskModel] to a map.
  Map<String, dynamic> toMap() => {
    'id': id,
    'timestamp': timestamp.millisecondsSinceEpoch ~/ 1000,
    'level': level,
    'message': message,
    'createdAt': createdAt.millisecondsSinceEpoch ~/ 1000,
    'updatedAt': updatedAt.millisecondsSinceEpoch ~/ 1000,
  };

  /// Copy with method
  LogModel copyWith({
    int? id,
    DateTime? timestamp,
    int? level,
    String? message,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) => LogModel(
    id: id ?? this.id,
    timestamp: timestamp ?? this.timestamp,
    level: level ?? this.level,
    message: message ?? this.message,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
  );

  /// The unique identifier for the log entry.
  final int id;

  /// The timestamp of the log entry.
  final DateTime timestamp;

  /// The level of the log entry (a value between 0 and 6).
  final int level;

  /// The message of the log entry.
  final String message;

  /// The creation date of the log entry.
  final DateTime createdAt;

  /// The last update date of the log entry.
  final DateTime updatedAt;
}
