import 'package:database/src/sql_database.dart';

/// Type definition for a weekly task reward id.
typedef WeeklyTaskRewardId = int;

/// {@template weekly_task_reward}
/// Model for a weekly task reward.
/// {@endtemplate}
class WeeklyTaskRewardModel {
  /// {@macro weekly_task_reward}
  WeeklyTaskRewardModel({
    required this.id,
    required this.title,
    required this.description,
    required this.goalWeight,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Creates a new [WeeklyTaskRewardModel] without an ID (for insertion).
  /// The ID will be auto-generated by the database.
  WeeklyTaskRewardModel.create({
    required this.title,
    required this.description,
    required this.goalWeight,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) : id = 0,
       createdAt = createdAt ?? DateTime.now(),
       updatedAt = updatedAt ?? DateTime.now();

  /// Creates a [WeeklyTaskRewardModel] from a a [WeeklyTaskReward] table instance.
  factory WeeklyTaskRewardModel.fromTable(WeeklyTaskReward data) => WeeklyTaskRewardModel(
    id: data.id,
    title: data.title,
    description: data.description,
    goalWeight: data.goalWeight,
    createdAt: data.createdAt,
    updatedAt: data.updatedAt,
  );

  /// Converts the [WeeklyTaskRewardModel] to a map.
  Map<String, dynamic> toMap() => {
    'id': id,
    'title': title,
    'description': description,
    'goalWeight': goalWeight,
    'createdAt': createdAt.millisecondsSinceEpoch ~/ 1000,
    'updatedAt': updatedAt.millisecondsSinceEpoch ~/ 1000,
  };

  /// Copy with method
  WeeklyTaskRewardModel copyWith({
    int? id,
    String? title,
    String? description,
    int? goalWeight,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) => WeeklyTaskRewardModel(
    id: id ?? this.id,
    title: title ?? this.title,
    description: description ?? this.description,
    goalWeight: goalWeight ?? this.goalWeight,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
  );

  /// The unique identifier for the task.
  final int id;

  /// The title of the task.
  final String title;

  /// The description of the task.
  final String? description;

  /// The weight of the task.
  final int goalWeight;

  /// The date and time the task was created.
  final DateTime createdAt;

  /// The date and time the task was last updated.
  final DateTime updatedAt;
}
